language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: QA7SbiMwZSPh0vXEab/OJeY/X0j/68+bzMJLAGu2eS0CmBjkk7IfqZXeo3cic1ic0qRJR59GPG7cS4AbjBNTQUr/jFjQfyJkAm1HQI4ZYXW8YUHoVG9KeeX3x69MwvgkGJsX6lZYULh3FK6wB9fHZdVussEoNePnxLHZ42LJn1iBg5VLbbjeitSFhY87McluAbMBBONSLp7VdUgV1/XYIrS6jEmiiAzKf7Kie+0gZYfElca6ARi3HHYy9wFb80uqbT9kWYp9IqQliTeNsAYrlPMG7mzPcmDDEwAhO2CyeabVcuzgs1As+wZJzFDv5UfBtcyNOR2ru46l3AG3eah36mdTpsXLHBXzKXF2rOIEmVVQeLy/We0PRuHmuYh8M0vq/eVTK65WoxmAVQPbt/KGzi4EHC2u+Zr18yPE0IFiYRTpXQLgWLsyvHgDDSsHsdQVenfoJbOX9aaNNHMeAVaISKJJjlw4vT7nA6taZETEdi0mTXoVqpZSHtFdEvDXSQGveOuTjdQyjeTCB387lxyBAvwckYs+i/opKKy9t60wHxsWZH0CylU/ExcsIHcBNO8LtM+fHUQ3RBT/qm9bk5PZY8dbOntihkMZFsokXnZAFnYJsXu95CWngpwlXnNeHzZarlgjiu9JjglZ+pEN0edl+r5BwBZfpL0NtpMkHEhp5F8
  app: vast-fortress-75083
  on:
    repo: ssan9/MyBucketList-server
