language: node_js
node_js: node
deploy:
  provider: heroku
  api_key: 
    secure: ARhSi6y0R74D2PpSq/3xkFthqjxiWqU/MPkaERlvA/ePKaaSBUn6VUs2LEKrUfPtGfN9vDN23SuP78UqZIcXpHeelcjQ+qKGg8l85QvEv3VhFsQHyWDlKwcpgeIsEgIIZGNK6Ji8XRU3WyBFCj7BqiuXZZzUs5IRumUr2xwDFsQtsKqCRI6Z/CvN/RznfkYNp7AvxxoXg/cjQmq0GpzP8AA7CgQXYSTml/VzJ421i4UgMn/mRdxoRgjKlho18KrQXlWdaeWyQo3z84OTlZkRTsMNWs/Cxy3KQ6xQAg9bKHAi1N5OzRhT5fzFtCd9r3oDQvHFzBMvZyDSZGbKqFtGvZn77sSxXQzuCs2pBocPTra3KBRxzl04gQ5GZ00yZfVpxgSvfV8w9DbkWxop6kthduPlv0FP2QwUm9YqgtrifLt5BTm7pcJ29m57V6C+czodybEp/x+pe+3qibF+iDVIV1gEZ5VUSfbVVSuRa9CU/B8yBSLB5qym/l2sKbYdX47n0OU2tzz6Hk6r7CejDzxXPq5Q5kb0IGinZpp1EDcxHJCcM1mci0aoCrJZD0gssFW5Vk3txdQ/5+I2k3nTgb2JT5KmT413QYOJEfStKjYsR2HLXxf8pWD7r1FheOsPF3Re05VFNi/mHJZOWhoQ0qj2X8JlNcWU7gjppvLTTNiNzzM=
  app: vast-fortress-75083
  on:
    repo: ssan9/MyBucketList-server
